apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb
spec:
  minAvailable: 2 # Specify the minimum number of pods that must be available
  selector:
    matchLabels:
      app: my-app # Label selector to match the pods for this PDB
