apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup
  labels: 
    app: readiness 
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: readiness
 template:
    metadata:
      labels:
        app: readiness
    spec:
      containers:
      - name: nginx
        image: lovelearnlinux/webserver:v1
        ports:
        - containerPort: 80
        startupProbe:
          exec:
            command:
            - cat
            - /var/www/html/index.html
          periodSeconds: 10
          failureThreshold: 3
         
            
  
