alertmanager:
  config:
    global:
      resolve_timeout: 5m
      startTLS_policy: NoStartTLS # Add this line to disable STARTTLS
    route:
      group_by: ['severity']
      group_interval: 5m
      group_wait: 30s
      repeat_interval: 3h
      receiver: email-alerts
    receivers:
      - name: email-alerts
        email_configs:
          - to: your-email@example.com
