valertmanager:
  config:
    global:
      # Global Alertmanager configuration (if needed)
    route:
      group_by: ['severity']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: email-alerts
    receivers:
      - name: email-alerts
        email_configs:
          - to: your-email@example.com
